Repository CMU-313/spring23-nodebb-team-tbd, pull requests merged in 2023-02, with the labels that each got.

#20 Fix poll button not working
  nodebb-plugin-poll-modified/public/js/poll/main.js
  themes/nodebb-theme-persona/templates/header.tpl
Labels: bug

#22 added error validation check and option to choose view type
  nodebb-plugin-poll-modified/public/js/poll/creator.js
  nodebb-plugin-poll-modified/templates/poll/creator.tpl
Labels: enhancement

#30 Add poll progress bar color and vertical rendering
  nodebb-plugin-markdown-modified/public/js/client.js
  nodebb-plugin-markdown-modified/websockets.js
  nodebb-plugin-poll-modified/lib/config.js
  nodebb-plugin-poll-modified/public/js/poll/creator.js
  nodebb-plugin-poll-modified/public/js/poll/serializer.js
  nodebb-plugin-poll-modified/templates/poll/creator.tpl
  nodebb-plugin-poll-modified/templates/poll/view.tpl
  nodebb-plugin-poll-modified/templates/poll/view/results.tpl
Labels: enhancement

#29 Add poll plugin activation to build
  install/package.json
  nodebb-plugin-poll-modified/public/js/poll/main.js
  src/cli/index.js
  src/install.js
Labels: documentation
