Repository CMU-313/spring23-nodebb-team-tbd, pull requests merged in 2023-03, with the labels that each got.

#35 Fix lint errors in admin.js
  nodebb-plugin-markdown-modified/public/js/admin.js
Labels: bug

#28 Revert "Add latex button feature is implemented"
  nodebb-plugin-markdown-modified/.eslintrc
  nodebb-plugin-markdown-modified/.jshintrc
  nodebb-plugin-markdown-modified/README.md
  nodebb-plugin-markdown-modified/commitlint.config.js
  nodebb-plugin-markdown-modified/index.js
  nodebb-plugin-markdown-modified/lib/controllers.js
  nodebb-plugin-markdown-modified/package.json
  nodebb-plugin-markdown-modified/plugin.json
  nodebb-plugin-markdown-modified/public/js/.eslintrc
  nodebb-plugin-markdown-modified/public/js/admin.js
  nodebb-plugin-markdown-modified/public/js/client.js
  nodebb-plugin-markdown-modified/public/languages/de/markdown.json
  nodebb-plugin-markdown-modified/public/languages/en-GB/markdown.json
  nodebb-plugin-markdown-modified/public/languages/fa-IR/markdown.json
  nodebb-plugin-markdown-modified/public/languages/fr/markdown.json
  nodebb-plugin-markdown-modified/public/languages/he/markdown.json
  nodebb-plugin-markdown-modified/public/languages/pl/markdown.json
  nodebb-plugin-markdown-modified/public/languages/ru/markdown.json
  nodebb-plugin-markdown-modified/public/languages/tr/markdown.json
  nodebb-plugin-markdown-modified/public/languages/zh-CN/markdown.json
  nodebb-plugin-markdown-modified/public/less/default.less
  nodebb-plugin-markdown-modified/public/templates/admin/plugins/markdown.tpl
  nodebb-plugin-markdown-modified/renovate.json
  nodebb-plugin-markdown-modified/upgrades/reset_md_hljs_theme.js
  nodebb-plugin-markdown-modified/upgrades/use_unminified_hljs_theme.js
  nodebb-plugin-markdown-modified/websockets.js
Labels: invalid

#36 Add tests for poll serializer feature
  install/package.json
  nodebb-plugin-poll-modified/public/js/poll/serializer.js
  nodebb-plugin-poll-modified/templates/poll/view/results.tpl
  test/poll.js
  test/poll.ts
Labels: enhancement

#39 Fixed the poll not rendering bug
  nodebb-plugin-poll-modified/public/js/poll/main.js
Labels: bug

#37 Adding color picker
  nodebb-plugin-poll-modified/templates/poll/creator.tpl
Labels: enhancement

#43 Fixed the vertical poll UI not updating bug
  nodebb-plugin-poll-modified/public/js/poll/view.js
  nodebb-plugin-poll-modified/templates/poll/view/results.tpl
Labels: bug

#49 Adds continuous deployment
  .github/workflows/fly.yml
  Dockerfile
  fly.toml
Labels: enhancement

#51 Fixed problem where app has to be built before deploying
  .github/workflows/fly.yaml
  Dockerfile
  fly.toml
  src/database/redis/connection.js
Labels: bug

#52 Deleting obviously duplicated workflow
  .github/workflows/fly.yml
Labels: bug

#54 Fixed correct workflow name for deployment
  .github/workflows/fly.yaml
Labels: bug
